apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1.20
  labels:
    app: nginx-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
        version: "1.20"
    spec:
      containers:
        - name: nginx
          image: nginx:1.20
          ports:
            - containerPort: 8080
